### ISSUE TITLE
Definition of Hz as 1/s doesn't work

### ISSUE THREAD

**Issue by jplatte** [zneak/units-cxx14#2]
I added it to `example.cpp` as a very simple testcase.

Code:

```
auto _Hz = 1 / _s;
```

g++ 4.9.2 error message:

```
In file included from example.cpp:26:0:
units.hpp: In instantiation of ‘constexpr typename std::enable_if<std::is_arithmetic<_Tp>::value, unitscxx::quantity<NT, N, D> >::type unitscxx::operator/(MulType, unitscxx::quantity<NT, N, D>) [with MulType = int; NT = double; N = detail::sequence<units, (units)1>; D = detail::sequence<units>; typename std::enable_if<std::is_arithmetic<_Tp>::value, unitscxx::quantity<NT, N, D> >::type = unitscxx::quantity<double, detail::sequence<units, (units)1>, detail::sequence<units> >]’:
example.cpp:43:16:   required from here
units.hpp:367:36: error: could not convert ‘unitscxx::quantity<double, detail::sequence<units>, detail::sequence<units> >((double)left).unitscxx::quantity<NumericType, Numerator, Denominator>::operator/<double, detail::sequence<units, (units)1>, detail::sequence<units> >(right)’ from ‘unitscxx::quantity<double, detail::sequence<units>, detail::sequence<units, (units)1> >’ to ‘std::enable_if<true, unitscxx::quantity<double, detail::sequence<units, (units)1>, detail::sequence<units> > >::type {aka unitscxx::quantity<double, detail::sequence<units, (units)1>, detail::sequence<units> >}’
   return unitless_quantity(left) / right;
                                    ^
units.hpp:368:2: error: body of constexpr function ‘constexpr typename std::enable_if<std::is_arithmetic<_Tp>::value, unitscxx::quantity<NT, N, D> >::type unitscxx::operator/(MulType, unitscxx::quantity<NT, N, D>) [with MulType = int; NT = double; N = detail::sequence<units, (units)1>; D = detail::sequence<units>; typename std::enable_if<std::is_arithmetic<_Tp>::value, unitscxx::quantity<NT, N, D> >::type = unitscxx::quantity<double, detail::sequence<units, (units)1>, detail::sequence<units> >]’ not a return-statement
  }
  ^
```

clang++ 3.5.0 error message:

```
In file included from example.cpp:26:
./units.hpp:367:10: error: no viable conversion from 'quantity<[...], sequence<[...], (no argument)>, sequence<[...], 1>>' to 'quantity<[...],
      sequence<[...], 1>, sequence<[...], (no argument)>>'
                return unitless_quantity(left) / right;
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
example.cpp:43:14: note: in instantiation of function template specialization 'unitscxx::operator/<int, double, detail::sequence<units, 1>,
      detail::sequence<units> >' requested here
auto _Hz = 1 / _s;
             ^
./units.hpp:228:13: note: candidate constructor not viable: no known conversion from 'unitscxx::quantity<double, detail::sequence<units>,
      detail::sequence<units, 1> >' to 'const unitscxx::quantity<double, detail::sequence<units, 1>, detail::sequence<units> > &' for 1st argument
                constexpr quantity(const quantity&) = default;
                          ^
./units.hpp:229:13: note: candidate constructor not viable: no known conversion from 'unitscxx::quantity<double, detail::sequence<units>,
      detail::sequence<units, 1> >' to 'unitscxx::quantity<double, detail::sequence<units, 1>, detail::sequence<units> > &&' for 1st argument
                constexpr quantity(quantity&&) = default;
                          ^
1 error generated.
```

Also, for everything else to work with g++ 4.9, I first had to make a small change to the header file (see the second revision of my gist). Anyway, I don't really understand what this error message says.

**Comment by fay59** [comment]
I'm looking into it.

**Comment by fay59** [comment]
Templates are notoriously ugly to debug, but I think that unitscxx is actually on the more straightforward side.

`quantity` represents an arithmetic value of type `NumericType` multiplied by units `Numerator` and divided by units `Denominator`. `Numerator` and `Denominator` are sequences of enum values (`detail::sequence<type, element1, element2, ...>`). So what it (gcc) is saying is:

```
units.hpp:367:36: error: could not convert ‘[mostly irrelevant]’ from:

unitscxx::quantity<double,
    detail::sequence<units>,            // multiplied by no units
    detail::sequence<units, (units)1> > // divided by (units)1: units::second
                                        // (double) / (units::second)
to:

[mostly irrelevant] {aka
unitscxx::quantity<double,
    detail::sequence<units, (units)1>, // multiplied by (units)1: units::second
    detail::sequence<units> >}         // (double) * (units::second)
```

This means that the return expression had type `1/_s` but the overload declared its type to be `1•_s`, which is wrong. It's a simple copy-paste error in the return type definition, the fix is to change `quantity<NT, N, D>` to `quantity<NT, D, N>` (since dividing flips the denominator and numerator around).

**Comment by jplatte** [comment]
Awesome, thanks a lot for the quick replies and fixes!
